### ISSUE TITLE
Stackdriver logging - client is not shut down properly

### ISSUE THREAD

**Issue by zohrehj** [GoogleCloudPlatform/fda-mystudies#2058]
Seeing in logs:
```
SEVERE [http-nio-8080-exec-4] io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.cleanQueue *~*~*~ Channel ManagedChannelImpl{logId=5, target=logging.googleapis.com:443} was not shutdown properly!!! ~*~*~*
 Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
		at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:94)
		at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:52)
		at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:43)
		at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:518)
		at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:304)
		at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1500(InstantiatingGrpcChannelProvider.java:71)
		at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:202)
		at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
		at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:209)
		at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:192)
		at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:155)
		at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:122)
		at com.google.cloud.logging.spi.v2.GrpcLoggingRpc.<init>(GrpcLoggingRpc.java:132)
		at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:61)
		at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:55)
		at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:538)
		at com.google.cloud.logging.LoggingOptions.getLoggingRpcV2(LoggingOptions.java:129)
		at com.google.cloud.logging.LoggingImpl.<init>(LoggingImpl.java:109)
		at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:46)
		at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:41)
		at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:518)
		at com.google.cloud.healthcare.fdamystudies.service.AuditEventServiceImpl.postAuditLogEvent(AuditEventServiceImpl.java:43)
		at com.google.cloud.healthcare.fdamystudies.common.UserMgmntAuditHelper.logEvent(UserMgmntAuditHelper.java:45)
		at com.google.cloud.healthcare.fdamystudies.common.UserMgmntAuditHelper.logEvent(UserMgmntAuditHelper.java:30)
		at com.google.cloud.healthcare.fdamystudies.service.UserRegistrationServiceImpl.register(UserRegistrationServiceImpl.java:96)
		at com.google.cloud.healthcare.fdamystudies.service.UserRegistrationServiceImpl$$FastClassBySpringCGLIB$$ce6a0d62.invoke(<generated>)
```

**Comment by aswinijena100** [comment]
@jkrogers18 This issue is fixed now and PR #3262 raised for the same. request you please verify and close this issue if fixed.

**Comment by aswinijena100** [comment]
@jkrogers18 fix for this issue merged with develop now. Could you please test and close this issue if fixed.

**Comment by aswinijena100** [comment]
PR #3262 merged with develop now , hence closing this ticket.
