### ISSUE TITLE
[Android] Study List is not Displaying Launched Studies

### ISSUE THREAD

**Issue by michael-intindola** [GoogleCloudPlatform/fda-mystudies#2850]
**Describe the bug**
I am currently building off of v2.0.1. 

I have followed the Android README instructions and configured values in `Android/app/build.gradle`, `Android/api.properties`, and `Android/app/src/fda/res/values/strings.xml`. I am able to successfully build and install the application on my device and have created a user, signed in, and created a passcode. I expect to see the study I configured in Study Builder to appear in the mobile application so my user can enroll. Instead, I see an empty screen (see attached photo) and in the debug logs I see the error:

```2021-01-14 12:27:42.792 19394-19394/com.mintindola.mikeystudies_dev.android E/RecyclerView: No adapter attached; skipping layout```

This error appears every time I navigate away from the Home Screen and then return Home. 

I have confirmed that the `API_KEY` in `Android/api.properties` is set correctly (`<auto-sd-android-id>`:`<auto-sd-android-token>`), taking the values directly from Secret Manager. 

**Expected behavior**
I expect to see the study I created in Study Builder to appear in the Android app

**Screenshots**
<img height="500" alt="Screenshot_20210114-123713" src="https://user-images.githubusercontent.com/46120033/104627981-af707300-5665-11eb-86f0-2806318e97b3.png">

**Comment by naveenr-btc** [comment]
Hi @michael-intindola please check if the study created is also available for android as well in studyBuilder. if so please confirm if API_KEY in api.properties below to android that's configured in authorizationResource.properties of studyDataStore.

**Comment by michael-intindola** [comment]
Hi @naveenr-btc ,
Confirming that the study is enabled for Android in StudyBuilder.
<img width="500" alt="Screen Shot 2021-01-18 at 10 45 46 AM" src="https://user-images.githubusercontent.com/46120033/104940461-c1148c00-597f-11eb-8202-88c6dde70d7a.png"> 

I believe I may have found some sort of discrepency in the naming/value of the Android ID used for API_KEY and I am a bit confused. In `Android/api.properties` it says:
```
# API_KEY is <android.bundleid>:<android.apptoken>
# These values should match the ones set in study datastore server.
# see: study-datastore/src/main/resources/authorizationResource.properties
# In terraform deployment these values are found in auto-sd-android-id and
# auto-sd-android-token secrets in your GCP secrets project.
```

When I look in `study-datastore/src/main/resources/authorizationResource.properties`, I see the following two properties set:
```
android.apptoken=${ANDROID_APP_TOKEN}
android.bundleid=${ANDROID_BUNDLE_ID}
```

In Secret Manager, Android Bundle ID is different than the Android ID. For example, the environment variable `ANDROID_BUNDLE_ID` is associated with the secret `manual-android-bundle-id` in the file `copy_app_info_to_sql.sh`, but  `ANDROID_BUNDLE_ID` is also given the value of `auto-sd-android-id` in `study-datastore/tf-deployment.yaml` (the Kubernetes secret `study-datastore-connect-credentials` has key `android_id` set to `auto-sd-android-id` as defined in `deployment/terraform/kubernetes/main.tf`)

Can you please confirm which value I should be using for the first portion of `API_KEY`? Is it `auto-sd-android-id` (an alphanumeric character string) or `manual-android-bundle-id` (`com.mintindola.mikeystudies_dev.android`)?

**Comment by michael-intindola** [comment]
@naveenr-btc  I am also seeing the following errors in my Kubernetes `study-datastore` logs:
```
INFO,"Hibernate: select appversion0_.version_info_id as version1_51_, appversion0_.android_force_update as android2_51_, appversion0_.android as android51_, appversion0_.app_id as app4_51_, appversion0_.ios_force_update as ios5_51_, appversion0_.ios as ios51_ from version_info appversion0_ where appversion0_.app_id=?
```
```
ERROR,"18-Jan-2021 16:50:38.325 WARNING [http-nio-8080-exec-5] org.hibernate.util.JDBCExceptionReporter.logExceptions SQL Error: 0, SQLState: 08S01
```
```
ERROR,"18-Jan-2021 16:50:38.330 SEVERE [http-nio-8080-exec-5] org.hibernate.util.JDBCExceptionReporter.logExceptions The last packet successfully received from the server was 339,355,230 milliseconds ago.  The last packet sent successfully to the server was 339,355,233 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
```
```
INFO,"2021-01-18 16:50:38,338 ERROR [http-nio-8080-exec-5] (AppMetaDataDao.java:556) - ERROR: AppMetaDataDao - getAppVersionInfo()
```
```
INFO,"org.hibernate.exception.JDBCConnectionException: could not execute query
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:99)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
	at org.hibernate.loader.Loader.doList(Loader.java:2452)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2192)
	at org.hibernate.loader.Loader.list(Loader.java:2187)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:452)
	at org.hibernate.hql.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:363)
	at org.hibernate.engine.query.HQLQueryPlan.performList(HQLQueryPlan.java:196)
	at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1258)
	at org.hibernate.impl.QueryImpl.list(QueryImpl.java:102)
	at org.hibernate.impl.AbstractQueryImpl.uniqueResult(AbstractQueryImpl.java:859)
	at com.hphc.mystudies.dao.AppMetaDataDao.getAppVersionInfo(AppMetaDataDao.java:554)
	at com.hphc.mystudies.integration.AppMetaDataOrchestration.getAppVersionInfo(AppMetaDataOrchestration.java:131)
	at com.hphc.mystudies.service.StudyMetaDataService.getAppVersionInfo(StudyMetaDataService.java:943)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ObjectOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:258)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.hphc.mystudies.web.servlet.RestAuthenticationFilter.doFilter(RestAuthenticationFilter.java:56)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:666)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 339,355,230 milliseconds ago.  The last packet sent successfully to the server was 339,355,233 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1074)
	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3313)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1940)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2109)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2643)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2077)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2228)
	at org.hibernate.jdbc.AbstractBatcher.getResultSet(AbstractBatcher.java:208)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:1869)
	at org.hibernate.loader.Loader.doQuery(Loader.java:718)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:270)
	at org.hibernate.loader.Loader.doList(Loader.java:2449)
	... 56 more
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3294)
	... 66 more
",2021-01-18T16:50:38.345370243Z
```

**Comment by naveenr-btc** [comment]
Hi, @aswinijena100 please check and provide info to @michael-intindola of what needs to be done for this issue.

**Comment by naveenr-btc** [comment]
@michael-intindola can you also confirm if the appId is configured correctly in the mobile app which was given in study builder

**Comment by michael-intindola** [comment]
Hi @naveenr-btc ,
I believe the appId (MIKEYSTUDIES) is set correctly in the Study Builder, Secret Manager, and Android Mobile App. See below screenshots:

_Study Builder:_
<img width="500" alt="Screen Shot 2021-01-20 at 10 38 50 AM" src="https://user-images.githubusercontent.com/46120033/105199831-382b5b00-5b0d-11eb-845a-f81f8316f88c.png">

_Secret Manager:_
<img width="500" alt="Screen Shot 2021-01-20 at 10 39 55 AM" src="https://user-images.githubusercontent.com/46120033/105199862-411c2c80-5b0d-11eb-959d-779ffa184a42.png">

_Android Mobile App:_
<img width="500" alt="Screen Shot 2021-01-20 at 10 41 13 AM" src="https://user-images.githubusercontent.com/46120033/105199895-48433a80-5b0d-11eb-978d-f1ebf5880bbb.png">

**Comment by michael-intindola** [comment]
@aswinijena100 @naveenr-btc any update on this? any suspicion for why the studies are not appearing in the Android mobile application? Should I try with iOS and see if they appear there?

**Comment by aswinijena100** [comment]
@michael-intindola Sorry for the delay in replying.

As per the logs shared from study-datastore , I can see database connection was not able to established. Please refer this.  [SQLState: 08S01](https://stackoverflow.com/questions/16459990/sql-error-0-sqlstate-08s01-communications-link-failure)

**Comment by michael-intindola** [comment]
@aswinijena100 I am not really sure how to modify the database connection settings and what settings to change? I am assuming the settings for the Study Datastore are in `study-datastore/source/main/resources/hibernate.cfg.xml`. 

I may be completely wrong, but it seems as if the method that asks for the Study List is not able to even utilize the cloudsql-proxy in the study-datastore pod. Everytime I navigate away from the Home screen and then back, I see the query logs in the study-datastore container but I don't see any connections being opened/closed in the cloudsql-proxy container. 

Study Datastore:
<img width="800" alt="Screen Shot 2021-01-22 at 3 16 46 PM" src="https://user-images.githubusercontent.com/46120033/105540880-f1806100-5cc4-11eb-8807-fa9b328fce5f.png">

Cloud SQL Proxy:
<img width="800" alt="Screen Shot 2021-01-22 at 3 15 58 PM" src="https://user-images.githubusercontent.com/46120033/105540964-11b02000-5cc5-11eb-8ee1-b353d00ca6e8.png">

I also see an error in the Study Datastore pod now for the RestAuthenticationFilter. Any idea what this is from and if it could be related?

**Comment by aswinijena100** [comment]
@michael-intindola Database details are configured in application.properties. Request you to please reverify the DB properties. Also  could you please try healthcheck for the study datastore and see if it successfully deployed. The endpoint for the  same is /healthCheck

**Comment by alanhughes** [comment]
I'm seeing this in my build off 2.0.1 as well. I spent some time digging through the code to see what the issue was, as far as I can tell the `user_details_id` column in the `participant_study_id` column is not getting populated when a user is created for a study. as a result, the call to `/participant-enroll-datastore/studyState`, which is one of two requests made according to the Android Studio profiler when the studyList screen is refreshed (along with`studyDatastore/studyList`), is returning an empty list of studies. The studyList endpoint returned the expected study.

I've not dug deeper into why that column is not being populated, but when I fill it manually with the value of the `id` column from the relevant row in `user_details` the study is returned according to the profiler - however the screen remains blank. I'm no Android expert so have been unable to diagnose further at this stage why the study list remains blank in the app UI even when the study information is returned by the endpoint. @michael-intindola I would recommend setting up the profiler in Android Studio if you get a chance and have a look in the network panel at the request/response payloads.

**Comment by michael-intindola** [comment]
Hi @aswinijena100,
I confirmed that the healthCheck for study-datastore is returning "200 OK" (see below).

<img width="650" alt="Screen Shot 2021-01-25 at 11 49 46 AM" src="https://user-images.githubusercontent.com/46120033/105750165-5e3c6b00-5f12-11eb-85dc-221da4533184.png">

I also re-verified the DB properties in `study-datastore/source/main/resources/application.properties`. The correct `DB_NAME`, `DB_USER`, and `DB_PASSWORD` are set in the Kubernetes secret and are being set as environment variables in the `study-datastore` container.

Do you recommend I try deploying off another branch that you know will work?

**Comment by michael-intindola** [comment]
@alanhughes I am glad you are able to replicate this issue in v2.0.1. Great idea setting up the Profiler in Android Studio! I will do this now to get a better look at the network traffic.

**Comment by naveenr-btc** [comment]
Hi, @michael-intindola like @alanhughes suggests please check if "studyDatastore/studyList" is returning any studies. It'll help to streamline where the issue is.

**Comment by michael-intindola** [comment]
@naveenr-btc @aswinijena100 I was able to get my study to appear in the Study List view and was able to join the study and progress through onboarding!! I believe the ONLY change that I made was I added iOS as a supported platform in the Study Builder screen (see below). I also updated the iOS related secrets and ran the `deployment/scripts/copy_app_info_to_sql.sh` script to update the participant datastore. When I went into the Android app, my study finally appeared. Not too sure what could have caused this but it seems like launching a study for **Android only** causes problems.

<img width="758" alt="Screen Shot 2021-01-27 at 4 43 44 PM" src="https://user-images.githubusercontent.com/46120033/106058261-0131e800-60bf-11eb-8d45-3848dbd41481.png">

**Comment by alanhughes** [comment]
Great find @michael-intindola ! I confirm i see the same thing - ran a fresh environment, created a study with BOTH platforms supported, and I'm able to enroll and enter data no problem. Definitely seems like a bug with studies that are only configured to support android

**Comment by naveenr-btc** [comment]
Hi, @michael-intindola @alanhughes glad to know it's working for you guys. we'll try to analysis and fix this issue.

**Comment by naveenr-btc** [comment]
@aswinijena100 please check based on the scenario that's mentioned above.

**Comment by aswinijena100** [comment]
@michael-intindola @alanhughes Request you to take latest release v2.0.2 and this issue could not be reproduced in the latest code. This should most likely resolve the issue for you.
