### ISSUE TITLE
[SB] [QA] Server error message is displaying randomly in different screens in the Study Builder

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#4561]
Steps:- 
1. Login into the app 
2. Navigate to different screens
3. Add/delete any records in the screens such as Questionnaires and observe

A/R:- Server error message is displaying randomly in different screens while performing any actions
E/R:- Server error message should not happen if server is up and running 

![image](https://user-images.githubusercontent.com/60500517/164445108-d05c0efc-252a-4972-8c32-5a6c980a84c1.png)

**Comment by harisboston** [comment]
Found below error in logs 

```
2022-04-21 04:31:39,912  WARN [http-nio-8080-exec-3] (SqlExceptionHelper.java:137) - SQL Error: 1205, SQLState: 40001
2022-04-21 04:31:39,914 ERROR [http-nio-8080-exec-3] (SqlExceptionHelper.java:142) - Lock wait timeout exceeded; try restarting transaction
2022-04-21 04:31:39,916 ERROR [http-nio-8080-exec-11] (StudyServiceImpl.java:611) - StudyServiceImpl - markAsCompleted() - Error
org.hibernate.TransactionException: Unable to rollback against JDBC Connection
        at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.rollback(AbstractLogicalConnectionImplementor.java:127)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.rollback(JdbcResourceLocalTransactionCoordinatorImpl.java:304)
        at org.hibernate.engine.transaction.internal.TransactionImpl.rollback(TransactionImpl.java:142)
        at com.fdahpstudydesigner.dao.StudyDAOImpl.markAsCompleted(StudyDAOImpl.java:2474)
        at com.fdahpstudydesigner.service.StudyServiceImpl.markAsCompleted(StudyServiceImpl.java:609)
        at com.fdahpstudydesigner.controller.StudyQuestionnaireController.viewStudyQuestionnaires(StudyQuestionnaireController.java:3033)
        at jdk.internal.reflect.GeneratedMethodAccessor373.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.fdahpstudydesigner.util.SessionFilter.doFilter(SessionFilter.java:35)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.fdahpstudydesigner.util.CrossScriptingFilter.doFilter(CrossScriptingFilter.java:49)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)

Caused by: java.sql.SQLNonTransientConnectionException: Can't call rollback when autocommit=true
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
        at com.mysql.cj.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:1823)
        at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.rollback(AbstractLogicalConnectionImplementor.java:121)
        ... 104 more


```

**Comment by akashkumarv3** [comment]
it is not replicating in dev env.

**Comment by akashkumarv3** [comment]
@nagarjunav1    Hi ,Please close this ticket as its similar to #4709 .

**Comment by nagarjunav1** [comment]
Closing this ticket and tracking it in the issue #4709
